//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace benim_kütüphanem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitapBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitapBilgi()
        {
            this.üyeKitapBilgi = new HashSet<üyeKitapBilgi>();
        }
    
        public int kitapId { get; set; }
        public string kitapAd { get; set; }
        public string kitapYazar { get; set; }
        public Nullable<System.DateTime> kitapYıl { get; set; }
        public Nullable<int> kitapSayfaSayisi { get; set; }
        public string kitapYayinEvi { get; set; }
        public string kitapDil { get; set; }
        public string kitapAcıklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<üyeKitapBilgi> üyeKitapBilgi { get; set; }
        public object KitapSayfaSayisi { get; internal set; }
    }
}
