//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace benim_kütüphanem.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class üyeKitapBilgi
    {
        public int okunanKitaplarId { get; set; }
        public string kitapAd { get; set; }
        public Nullable<System.DateTime> okunmaTarihi { get; set; }
        public Nullable<int> uyeId { get; set; }
        public Nullable<int> kitapId { get; set; }
    
        public virtual kitapBilgi kitapBilgi { get; set; }
        public virtual üyeBilgi üyeBilgi { get; set; }
    }
}
