//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace benim_kütüphanem.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class üyeBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public üyeBilgi()
        {
            this.üyeKitapBilgi = new HashSet<üyeKitapBilgi>();
        }
    
        public int uyeId { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public Nullable<int> uyeTelefon { get; set; }
        public string uyePosta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<üyeKitapBilgi> üyeKitapBilgi { get; set; }
    }
}
